import Head from "next/head"

const Heading = () => {

    return (

        <>
            <Head>
                <title>app title</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
        </>

    )

}

export default Heading